### PR TITLE
Check if param sheetCell is defined in getSheetCellValue()

### PR DESCRIPTION
**Pull request by ITesic**
I was trying to convert one large excel file and for some reason it was failing. I added one check in getSheetCellValue() method to protect it from crash if sheetCell is undefined.

screen shot 2018-10-16 at 21 51 04

### CODE REVIEW

**Comment by DiegoZoracKy** [comment]
Hi @ITesic, thanks for catching this and for pushing this PR. Can you please give me some more info about your case? What was the size of the file that resulted in error and how was your config object for the lib? Were you using the `{{columnHeaders}}` or defining your own `columnToKeys`?

**Comment by ITesic** [comment]
Hey @DiegoZoracKy,
I was using `{{columnHeaders}}`. The file that I was parsing is database dump with ~40 columns and >10000 rows. I couldn't trace exact cause for this issue, but since I needed the lib, I introduced this fix.

**Comment by DiegoZoracKy** [comment]
Yes, your PR is really useful. I'm asking you just because I'll try to
trace the root cause of the problem. Can you tell me the size of the file
(e.g. ~100mb).

**Comment by ITesic** [comment]
It's not that big, around 3MB. Extension is .xslx and header row has filters. There is Security warning when I open it in Excel, maybe that caused the issue.

screen shot 2018-10-17 at 22 11 00

**Comment by DiegoZoracKy** [comment]
Thanks @ITesic! Your PR is already merged and published on npm (v 1.5.1)

**Pull request merged**
