### PR TITLE
able to use Buffer as a source instead of sourceFile.

### PR DESCRIPTION
**Pull request by burib**
sometimes you want to convert a source that doesn't exists in filesystem.

since https://github.com/SheetJS/js-xlsx also handles buffers, let's give the option here as well.

### CODE REVIEW

**Comment by DiegoZoracKy** [comment]
Wow, that's very nice. I really wanted to have support for that and also support to handle the conversion in a async way. I will take a look on it on next week. 

Thanks;

**Comment by DiegoZoracKy** [comment]
Hi @burib,

Could you bump the version on package.json to 1.6.0? Having that I will merge your PR right away.

**Comment by burib** [comment]
@DiegoZoracKy thanks for the acceptance.

**Comment by burib** [comment]
@DiegoZoracKy could you please publish the new version to npm ?
thx.

**Comment by DiegoZoracKy** [comment]
Published! And thank you @burib for sending this PR.

**Comment by burib** [comment]
@shefaliA how about the one here? https://github.com/DiegoZoracKy/convert-excel-to-json#converting-an-xlsx-that-you-have-as-a-buffer

**Pull request merged**
